#![no_std]
// Generated upstream UEFI x64 compile-time checks; no Omega execution.
use core::mem::{size_of, align_of, offset_of};
const _: () = {
assert!(size_of::<uefi_raw::protocol::console::AbsolutePointerModeAttributes>() == 4);
assert!(align_of::<uefi_raw::protocol::console::AbsolutePointerModeAttributes>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_min_x) == 0);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_min_y) == 8);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_min_z) == 16);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_max_x) == 24);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_max_y) == 32);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, absolute_max_z) == 40);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerMode, attributes) == 48);
assert!(size_of::<uefi_raw::protocol::console::AbsolutePointerMode>() == 56);
assert!(align_of::<uefi_raw::protocol::console::AbsolutePointerMode>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerState, current_x) == 0);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerState, current_y) == 8);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerState, current_z) == 16);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerState, active_buttons) == 24);
assert!(size_of::<uefi_raw::protocol::console::AbsolutePointerState>() == 32);
assert!(align_of::<uefi_raw::protocol::console::AbsolutePointerState>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerProtocol, reset) == 0);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerProtocol, get_state) == 8);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerProtocol, wait_for_input) == 16);
assert!(offset_of!(uefi_raw::protocol::console::AbsolutePointerProtocol, mode) == 24);
assert!(size_of::<uefi_raw::protocol::console::AbsolutePointerProtocol>() == 32);
assert!(align_of::<uefi_raw::protocol::console::AbsolutePointerProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::InputKey, scan_code) == 0);
assert!(offset_of!(uefi_raw::protocol::console::InputKey, unicode_char) == 2);
assert!(size_of::<uefi_raw::protocol::console::InputKey>() == 4);
assert!(align_of::<uefi_raw::protocol::console::InputKey>() == 2);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputProtocol, reset) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputProtocol, read_key_stroke) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputProtocol, wait_for_key) == 16);
assert!(size_of::<uefi_raw::protocol::console::SimpleTextInputProtocol>() == 24);
assert!(align_of::<uefi_raw::protocol::console::SimpleTextInputProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::KeyData, key) == 0);
assert!(offset_of!(uefi_raw::protocol::console::KeyData, key_state) == 4);
assert!(size_of::<uefi_raw::protocol::console::KeyData>() == 12);
assert!(align_of::<uefi_raw::protocol::console::KeyData>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::KeyState, key_shift_state) == 0);
assert!(offset_of!(uefi_raw::protocol::console::KeyState, key_toggle_state) == 4);
assert!(size_of::<uefi_raw::protocol::console::KeyState>() == 8);
assert!(align_of::<uefi_raw::protocol::console::KeyState>() == 4);
assert!(size_of::<uefi_raw::protocol::console::KeyShiftState>() == 4);
assert!(align_of::<uefi_raw::protocol::console::KeyShiftState>() == 4);
assert!(size_of::<uefi_raw::protocol::console::KeyToggleState>() == 1);
assert!(align_of::<uefi_raw::protocol::console::KeyToggleState>() == 1);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, reset) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, read_key_stroke_ex) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, wait_for_key_ex) == 16);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, set_state) == 24);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, register_key_notify) == 32);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextInputExProtocol, unregister_key_notify) == 40);
assert!(size_of::<uefi_raw::protocol::console::SimpleTextInputExProtocol>() == 48);
assert!(align_of::<uefi_raw::protocol::console::SimpleTextInputExProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, max_mode) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, mode) == 4);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, attribute) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, cursor_column) == 12);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, cursor_row) == 16);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputMode, cursor_visible) == 20);
assert!(size_of::<uefi_raw::protocol::console::SimpleTextOutputMode>() == 24);
assert!(align_of::<uefi_raw::protocol::console::SimpleTextOutputMode>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, reset) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, output_string) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, test_string) == 16);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, query_mode) == 24);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, set_mode) == 32);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, set_attribute) == 40);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, clear_screen) == 48);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, set_cursor_position) == 56);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, enable_cursor) == 64);
assert!(offset_of!(uefi_raw::protocol::console::SimpleTextOutputProtocol, mode) == 72);
assert!(size_of::<uefi_raw::protocol::console::SimpleTextOutputProtocol>() == 80);
assert!(align_of::<uefi_raw::protocol::console::SimpleTextOutputProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerMode, resolution_x) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerMode, resolution_y) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerMode, resolution_z) == 16);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerMode, left_button) == 24);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerMode, right_button) == 25);
assert!(size_of::<uefi_raw::protocol::console::SimplePointerMode>() == 32);
assert!(align_of::<uefi_raw::protocol::console::SimplePointerMode>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerState, relative_movement_x) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerState, relative_movement_y) == 4);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerState, relative_movement_z) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerState, left_button) == 12);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerState, right_button) == 13);
assert!(size_of::<uefi_raw::protocol::console::SimplePointerState>() == 16);
assert!(align_of::<uefi_raw::protocol::console::SimplePointerState>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerProtocol, reset) == 0);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerProtocol, get_state) == 8);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerProtocol, wait_for_input) == 16);
assert!(offset_of!(uefi_raw::protocol::console::SimplePointerProtocol, mode) == 24);
assert!(size_of::<uefi_raw::protocol::console::SimplePointerProtocol>() == 32);
assert!(align_of::<uefi_raw::protocol::console::SimplePointerProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocol, query_mode) == 0);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocol, set_mode) == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocol, blt) == 16);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocol, mode) == 24);
assert!(size_of::<uefi_raw::protocol::console::GraphicsOutputProtocol>() == 32);
assert!(align_of::<uefi_raw::protocol::console::GraphicsOutputProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, max_mode) == 0);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, mode) == 4);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, info) == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, size_of_info) == 16);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, frame_buffer_base) == 24);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputProtocolMode, frame_buffer_size) == 32);
assert!(size_of::<uefi_raw::protocol::console::GraphicsOutputProtocolMode>() == 40);
assert!(align_of::<uefi_raw::protocol::console::GraphicsOutputProtocolMode>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, version) == 0);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, horizontal_resolution) == 4);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, vertical_resolution) == 8);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, pixel_format) == 12);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, pixel_information) == 16);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputModeInformation, pixels_per_scan_line) == 32);
assert!(size_of::<uefi_raw::protocol::console::GraphicsOutputModeInformation>() == 36);
assert!(align_of::<uefi_raw::protocol::console::GraphicsOutputModeInformation>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::PixelBitmask, red) == 0);
assert!(offset_of!(uefi_raw::protocol::console::PixelBitmask, green) == 4);
assert!(offset_of!(uefi_raw::protocol::console::PixelBitmask, blue) == 8);
assert!(offset_of!(uefi_raw::protocol::console::PixelBitmask, reserved) == 12);
assert!(size_of::<uefi_raw::protocol::console::PixelBitmask>() == 16);
assert!(align_of::<uefi_raw::protocol::console::PixelBitmask>() == 4);
assert!(size_of::<uefi_raw::protocol::console::GraphicsPixelFormat>() == 4);
assert!(align_of::<uefi_raw::protocol::console::GraphicsPixelFormat>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputBltPixel, blue) == 0);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputBltPixel, green) == 1);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputBltPixel, red) == 2);
assert!(offset_of!(uefi_raw::protocol::console::GraphicsOutputBltPixel, reserved) == 3);
assert!(size_of::<uefi_raw::protocol::console::GraphicsOutputBltPixel>() == 4);
assert!(align_of::<uefi_raw::protocol::console::GraphicsOutputBltPixel>() == 1);
assert!(size_of::<uefi_raw::protocol::console::GraphicsOutputBltOperation>() == 4);
assert!(align_of::<uefi_raw::protocol::console::GraphicsOutputBltOperation>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::EdidDiscoveredProtocol, size_of_edid) == 0);
assert!(offset_of!(uefi_raw::protocol::console::EdidDiscoveredProtocol, edid) == 8);
assert!(size_of::<uefi_raw::protocol::console::EdidDiscoveredProtocol>() == 16);
assert!(align_of::<uefi_raw::protocol::console::EdidDiscoveredProtocol>() == 8);
assert!(size_of::<uefi_raw::protocol::console::serial::ControlBits>() == 4);
assert!(align_of::<uefi_raw::protocol::console::serial::ControlBits>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, control_mask) == 0);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, timeout) == 4);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, baud_rate) == 8);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, receive_fifo_depth) == 16);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, data_bits) == 20);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, parity) == 24);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoMode, stop_bits) == 28);
assert!(size_of::<uefi_raw::protocol::console::serial::SerialIoMode>() == 32);
assert!(align_of::<uefi_raw::protocol::console::serial::SerialIoMode>() == 8);
assert!(size_of::<uefi_raw::protocol::console::serial::SerialIoProtocolRevision>() == 4);
assert!(align_of::<uefi_raw::protocol::console::serial::SerialIoProtocolRevision>() == 4);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, revision) == 0);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, reset) == 8);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, set_attributes) == 16);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, set_control_bits) == 24);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, get_control_bits) == 32);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, write) == 40);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, read) == 48);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol, mode) == 56);
assert!(size_of::<uefi_raw::protocol::console::serial::SerialIoProtocol>() == 64);
assert!(align_of::<uefi_raw::protocol::console::serial::SerialIoProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol_1_1, base_protocol) == 0);
assert!(offset_of!(uefi_raw::protocol::console::serial::SerialIoProtocol_1_1, device_type_guid) == 64);
assert!(size_of::<uefi_raw::protocol::console::serial::SerialIoProtocol_1_1>() == 72);
assert!(align_of::<uefi_raw::protocol::console::serial::SerialIoProtocol_1_1>() == 8);
assert!(size_of::<uefi_raw::protocol::console::serial::Parity>() == 4);
assert!(align_of::<uefi_raw::protocol::console::serial::Parity>() == 4);
assert!(size_of::<uefi_raw::protocol::console::serial::StopBits>() == 4);
assert!(align_of::<uefi_raw::protocol::console::serial::StopBits>() == 4);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, revision) == 0);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, parent_handle) == 8);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, system_table) == 16);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, device_handle) == 24);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, file_path) == 32);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, reserved) == 40);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, load_options_size) == 48);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, load_options) == 56);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, image_base) == 64);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, image_size) == 72);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, image_code_type) == 80);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, image_data_type) == 84);
assert!(offset_of!(uefi_raw::protocol::loaded_image::LoadedImageProtocol, unload) == 88);
assert!(size_of::<uefi_raw::protocol::loaded_image::LoadedImageProtocol>() == 96);
assert!(align_of::<uefi_raw::protocol::loaded_image::LoadedImageProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathProtocol, major_type) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathProtocol, sub_type) == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathProtocol, length) == 2);
assert!(size_of::<uefi_raw::protocol::device_path::DevicePathProtocol>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::DevicePathProtocol>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::DeviceType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::DeviceType>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::DeviceSubType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::DeviceSubType>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathToTextProtocol, convert_device_node_to_text) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathToTextProtocol, convert_device_path_to_text) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::DevicePathToTextProtocol>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::DevicePathToTextProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathFromTextProtocol, convert_text_to_device_node) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathFromTextProtocol, convert_text_to_device_path) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::DevicePathFromTextProtocol>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::DevicePathFromTextProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, get_device_path_size) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, duplicate_device_path) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, append_device_path) == 16);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, append_device_node) == 24);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, append_device_path_instance) == 32);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, get_next_device_path_instance) == 40);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, is_device_path_multi_instance) == 48);
assert!(offset_of!(uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol, create_device_node) == 56);
assert!(size_of::<uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol>() == 64);
assert!(align_of::<uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::end::Instance, header) == 0);
assert!(size_of::<uefi_raw::protocol::device_path::end::Instance>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::end::Instance>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::end::Entire, header) == 0);
assert!(size_of::<uefi_raw::protocol::device_path::end::Entire>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::end::Entire>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Pci, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Pci, function) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Pci, device) == 5);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::Pci>() == 6);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::Pci>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Pccard, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Pccard, function) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::Pccard>() == 5);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::Pccard>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::MemoryMapped, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::MemoryMapped, memory_type) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::MemoryMapped, start_address) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::MemoryMapped, end_address) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::MemoryMapped>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::MemoryMapped>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Vendor, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Vendor, vendor_guid) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Vendor, vendor_defined_data) == 20);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::Vendor>() == 20);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::Vendor>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Controller, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Controller, controller_number) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::Controller>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::Controller>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Bmc, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Bmc, interface_type) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::hardware::Bmc, base_address) == 5);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::Bmc>() == 13);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::Bmc>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::hardware::BmcInterfaceType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::hardware::BmcInterfaceType>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Acpi, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Acpi, hid) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Acpi, uid) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::acpi::Acpi>() == 12);
assert!(align_of::<uefi_raw::protocol::device_path::acpi::Acpi>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Expanded, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Expanded, hid) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Expanded, uid) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Expanded, cid) == 12);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Expanded, data) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::acpi::Expanded>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::acpi::Expanded>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Adr, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Adr, adr) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::acpi::Adr>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::acpi::Adr>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Nvdimm, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::acpi::Nvdimm, nfit_device_handle) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::acpi::Nvdimm>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::acpi::Nvdimm>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Atapi, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Atapi, primary_secondary) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Atapi, master_slave) == 5);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Atapi, logical_unit_number) == 6);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Atapi>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Atapi>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Scsi, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Scsi, target_id) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Scsi, logical_unit_number) == 6);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Scsi>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Scsi>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannel, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannel, _reserved) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannel, world_wide_name) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannel, logical_unit_number) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::FibreChannel>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::FibreChannel>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannelEx, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannelEx, _reserved) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannelEx, world_wide_name) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::FibreChannelEx, logical_unit_number) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::FibreChannelEx>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::FibreChannelEx>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ieee1394, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ieee1394, _reserved) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ieee1394, guid) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ieee1394>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ieee1394>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Usb, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Usb, parent_port_number) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Usb, interface) == 5);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Usb>() == 6);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Usb>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sata, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sata, hba_port_number) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sata, port_multiplier_port_number) == 6);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sata, logical_unit_number) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Sata>() == 10);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Sata>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbWwid, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbWwid, interface_number) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbWwid, device_vendor_id) == 6);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbWwid, device_product_id) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbWwid, serial_number) == 10);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::UsbWwid>() == 10);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::UsbWwid>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::DeviceLogicalUnit, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::DeviceLogicalUnit, logical_unit_number) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::DeviceLogicalUnit>() == 5);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::DeviceLogicalUnit>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, vendor_id) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, product_id) == 6);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, device_class) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, device_subclass) == 9);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::UsbClass, device_protocol) == 10);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::UsbClass>() == 11);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::UsbClass>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::I2o, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::I2o, target_id) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::I2o>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::I2o>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::MacAddress, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::MacAddress, mac_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::MacAddress, interface_type) == 36);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::MacAddress>() == 37);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::MacAddress>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, local_ip_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, remote_ip_address) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, local_port) == 12);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, remote_port) == 14);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, protocol) == 16);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, ip_address_origin) == 18);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, gateway_ip_address) == 19);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv4, subnet_mask) == 23);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ipv4>() == 27);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ipv4>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, local_ip_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, remote_ip_address) == 20);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, local_port) == 36);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, remote_port) == 38);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, protocol) == 40);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, ip_address_origin) == 42);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, prefix_length) == 43);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ipv6, gateway_ip_address) == 44);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ipv6>() == 60);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ipv6>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Vlan, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Vlan, vlan_id) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Vlan>() == 6);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Vlan>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, resource_flags) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, port_gid) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, ioc_guid_or_service_id) == 24);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, target_port_id) == 32);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Infiniband, device_id) == 40);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Infiniband>() == 48);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Infiniband>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, _reserved) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, baud_rate) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, data_bits) == 16);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, parity) == 17);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uart, stop_bits) == 18);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Uart>() == 19);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Uart>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Vendor, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Vendor, vendor_guid) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Vendor, vendor_defined_data) == 20);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Vendor>() == 20);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Vendor>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::SasEx, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::SasEx, sas_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::SasEx, logical_unit_number) == 12);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::SasEx, info) == 20);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::SasEx, relative_target_port) == 22);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::SasEx>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::SasEx>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, protocol) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, options) == 6);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, logical_unit_number) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, target_portal_group_tag) == 16);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Iscsi, iscsi_target_name) == 18);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Iscsi>() == 18);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Iscsi>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeNamespace, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeNamespace, namespace_identifier) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeNamespace, ieee_extended_unique_identifier) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::NvmeNamespace>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::NvmeNamespace>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uri, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Uri, value) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Uri>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Uri>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ufs, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ufs, target_id) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Ufs, logical_unit_number) == 5);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ufs>() == 6);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ufs>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sd, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Sd, slot_number) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Sd>() == 5);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Sd>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Bluetooth, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Bluetooth, device_address) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Bluetooth>() == 10);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Bluetooth>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Wifi, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Wifi, ssid) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Wifi>() == 36);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Wifi>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Emmc, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Emmc, slot_number) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Emmc>() == 5);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Emmc>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::BluetoothLe, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::BluetoothLe, device_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::BluetoothLe, address_type) == 10);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::BluetoothLe>() == 11);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::BluetoothLe>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Dns, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Dns, address_type) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::Dns, addresses) == 5);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Dns>() == 5);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Dns>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvdimmNamespace, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvdimmNamespace, uuid) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::NvdimmNamespace>() == 20);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::NvdimmNamespace>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::RestService, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::RestService, service_type) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::RestService, access_mode) == 5);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::RestService, vendor_guid_and_data) == 6);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::RestService>() == 6);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::RestService>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeOfNamespace, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeOfNamespace, nidt) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeOfNamespace, nid) == 5);
assert!(offset_of!(uefi_raw::protocol::device_path::messaging::NvmeOfNamespace, subsystem_nqn) == 21);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::NvmeOfNamespace>() == 21);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::NvmeOfNamespace>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::PrimarySecondary>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::PrimarySecondary>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::MasterSlave>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::MasterSlave>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ipv4AddressOrigin>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ipv4AddressOrigin>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Ipv6AddressOrigin>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Ipv6AddressOrigin>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags>() == 4);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::Parity>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::Parity>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::StopBits>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::StopBits>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::IscsiProtocol>() == 2);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::IscsiProtocol>() == 2);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::IscsiLoginOptions>() == 2);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::IscsiLoginOptions>() == 2);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::BluetoothLeAddressType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::BluetoothLeAddressType>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::DnsAddressType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::DnsAddressType>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::RestServiceType>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::RestServiceType>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::messaging::RestServiceAccessMode>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::messaging::RestServiceAccessMode>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, partition_number) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, partition_start) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, partition_size) == 16);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, partition_signature) == 24);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, partition_format) == 40);
assert!(offset_of!(uefi_raw::protocol::device_path::media::HardDrive, signature_type) == 41);
assert!(size_of::<uefi_raw::protocol::device_path::media::HardDrive>() == 42);
assert!(align_of::<uefi_raw::protocol::device_path::media::HardDrive>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::CdRom, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::CdRom, boot_entry) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::media::CdRom, partition_start) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::media::CdRom, partition_size) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::media::CdRom>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::media::CdRom>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::Vendor, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::Vendor, vendor_guid) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::media::Vendor, vendor_defined_data) == 20);
assert!(size_of::<uefi_raw::protocol::device_path::media::Vendor>() == 20);
assert!(align_of::<uefi_raw::protocol::device_path::media::Vendor>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::FilePath, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::FilePath, path_name) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::media::FilePath>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::media::FilePath>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::Protocol, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::Protocol, protocol_guid) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::media::Protocol>() == 20);
assert!(align_of::<uefi_raw::protocol::device_path::media::Protocol>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::PiwgFirmwareFile, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::PiwgFirmwareFile, data) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::media::PiwgFirmwareFile>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::media::PiwgFirmwareFile>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::PiwgFirmwareVolume, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::PiwgFirmwareVolume, data) == 4);
assert!(size_of::<uefi_raw::protocol::device_path::media::PiwgFirmwareVolume>() == 4);
assert!(align_of::<uefi_raw::protocol::device_path::media::PiwgFirmwareVolume>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RelativeOffsetRange, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RelativeOffsetRange, _reserved) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RelativeOffsetRange, starting_offset) == 8);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RelativeOffsetRange, ending_offset) == 16);
assert!(size_of::<uefi_raw::protocol::device_path::media::RelativeOffsetRange>() == 24);
assert!(align_of::<uefi_raw::protocol::device_path::media::RelativeOffsetRange>() == 1);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RamDisk, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RamDisk, starting_address) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RamDisk, ending_address) == 12);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RamDisk, disk_type) == 20);
assert!(offset_of!(uefi_raw::protocol::device_path::media::RamDisk, disk_instance) == 36);
assert!(size_of::<uefi_raw::protocol::device_path::media::RamDisk>() == 38);
assert!(align_of::<uefi_raw::protocol::device_path::media::RamDisk>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::media::PartitionFormat>() == 1);
assert!(align_of::<uefi_raw::protocol::device_path::media::PartitionFormat>() == 1);
assert!(size_of::<uefi_raw::protocol::device_path::media::RamDiskType>() == 16);
assert!(align_of::<uefi_raw::protocol::device_path::media::RamDiskType>() == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification, header) == 0);
assert!(offset_of!(uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification, device_type) == 4);
assert!(offset_of!(uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification, status_flag) == 6);
assert!(offset_of!(uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification, description_string) == 8);
assert!(size_of::<uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification>() == 8);
assert!(align_of::<uefi_raw::protocol::device_path::bios_boot_spec::BootSpecification>() == 1);
assert!(offset_of!(uefi_raw::protocol::media::LoadFileProtocol, load_file) == 0);
assert!(size_of::<uefi_raw::protocol::media::LoadFileProtocol>() == 8);
assert!(align_of::<uefi_raw::protocol::media::LoadFileProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::media::LoadFile2Protocol, load_file) == 0);
assert!(size_of::<uefi_raw::protocol::media::LoadFile2Protocol>() == 8);
assert!(align_of::<uefi_raw::protocol::media::LoadFile2Protocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::media::StorageSecurityCommandProtocol, receive_data) == 0);
assert!(offset_of!(uefi_raw::protocol::media::StorageSecurityCommandProtocol, send_data) == 8);
assert!(size_of::<uefi_raw::protocol::media::StorageSecurityCommandProtocol>() == 16);
assert!(align_of::<uefi_raw::protocol::media::StorageSecurityCommandProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::shell_params::ShellParametersProtocol, argv) == 0);
assert!(offset_of!(uefi_raw::protocol::shell_params::ShellParametersProtocol, argc) == 8);
assert!(offset_of!(uefi_raw::protocol::shell_params::ShellParametersProtocol, std_in) == 16);
assert!(offset_of!(uefi_raw::protocol::shell_params::ShellParametersProtocol, std_out) == 24);
assert!(offset_of!(uefi_raw::protocol::shell_params::ShellParametersProtocol, std_err) == 32);
assert!(size_of::<uefi_raw::protocol::shell_params::ShellParametersProtocol>() == 40);
assert!(align_of::<uefi_raw::protocol::shell_params::ShellParametersProtocol>() == 8);
assert!(size_of::<uefi_raw::protocol::console::KeyNotifyFn>() == 8);
assert!(align_of::<uefi_raw::protocol::console::KeyNotifyFn>() == 8);
assert!(size_of::<uefi_raw::protocol::shell_params::ShellFileHandle>() == 8);
assert!(align_of::<uefi_raw::protocol::shell_params::ShellFileHandle>() == 8);
assert!(uefi_raw::protocol::console::AbsolutePointerModeAttributes::SUPPORTS_ALT_ACTIVE.bits() == 1);
assert!(uefi_raw::protocol::console::AbsolutePointerModeAttributes::SUPPORTS_PRESSURE_AS_Z.bits() == 2);
assert!(uefi_raw::protocol::console::KeyShiftState::VALID.bits() == 2147483648);
assert!(uefi_raw::protocol::console::KeyShiftState::RIGHT_SHIFT.bits() == 1);
assert!(uefi_raw::protocol::console::KeyShiftState::LEFT_SHIFT.bits() == 2);
assert!(uefi_raw::protocol::console::KeyShiftState::RIGHT_CONTROL.bits() == 4);
assert!(uefi_raw::protocol::console::KeyShiftState::LEFT_CONTROL.bits() == 8);
assert!(uefi_raw::protocol::console::KeyShiftState::RIGHT_ALT.bits() == 16);
assert!(uefi_raw::protocol::console::KeyShiftState::LEFT_ALT.bits() == 32);
assert!(uefi_raw::protocol::console::KeyShiftState::RIGHT_LOGO.bits() == 64);
assert!(uefi_raw::protocol::console::KeyShiftState::LEFT_LOGO.bits() == 128);
assert!(uefi_raw::protocol::console::KeyShiftState::MENU_KEY.bits() == 256);
assert!(uefi_raw::protocol::console::KeyShiftState::SYS_REQ.bits() == 512);
assert!(uefi_raw::protocol::console::KeyToggleState::SCROLL_LOCK_ACTIVE.bits() == 1);
assert!(uefi_raw::protocol::console::KeyToggleState::NUM_LOCK_ACTIVE.bits() == 2);
assert!(uefi_raw::protocol::console::KeyToggleState::CAPS_LOCK_ACTIVE.bits() == 4);
assert!(uefi_raw::protocol::console::KeyToggleState::EXPOSED.bits() == 64);
assert!(uefi_raw::protocol::console::KeyToggleState::VALID.bits() == 128);
assert!(uefi_raw::protocol::console::GraphicsPixelFormat::PIXEL_RED_GREEN_BLUE_RESERVED_8_BIT_PER_COLOR.0 == 0);
assert!(uefi_raw::protocol::console::GraphicsPixelFormat::PIXEL_BLUE_GREEN_RED_RESERVED_8_BIT_PER_COLOR.0 == 1);
assert!(uefi_raw::protocol::console::GraphicsPixelFormat::PIXEL_BIT_MASK.0 == 2);
assert!(uefi_raw::protocol::console::GraphicsPixelFormat::PIXEL_BLT_ONLY.0 == 3);
assert!(uefi_raw::protocol::console::GraphicsPixelFormat::PIXEL_FORMAT_MAX.0 == 4);
assert!(uefi_raw::protocol::console::GraphicsOutputBltOperation::BLT_VIDEO_FILL.0 == 0);
assert!(uefi_raw::protocol::console::GraphicsOutputBltOperation::BLT_VIDEO_TO_BLT_BUFFER.0 == 1);
assert!(uefi_raw::protocol::console::GraphicsOutputBltOperation::BLT_BUFFER_TO_VIDEO.0 == 2);
assert!(uefi_raw::protocol::console::GraphicsOutputBltOperation::BLT_VIDEO_TO_VIDEO.0 == 3);
assert!(uefi_raw::protocol::console::GraphicsOutputBltOperation::GRAPHICS_OUTPUT_BLT_OPERATION_MAX.0 == 4);
assert!(uefi_raw::protocol::console::serial::ControlBits::CLEAR_TO_SEND.bits() == 16);
assert!(uefi_raw::protocol::console::serial::ControlBits::DATA_SET_READY.bits() == 32);
assert!(uefi_raw::protocol::console::serial::ControlBits::RING_INDICATE.bits() == 64);
assert!(uefi_raw::protocol::console::serial::ControlBits::CARRIER_DETECT.bits() == 128);
assert!(uefi_raw::protocol::console::serial::ControlBits::INPUT_BUFFER_EMPTY.bits() == 256);
assert!(uefi_raw::protocol::console::serial::ControlBits::OUTPUT_BUFFER_EMPTY.bits() == 512);
assert!(uefi_raw::protocol::console::serial::ControlBits::DATA_TERMINAL_READY.bits() == 1);
assert!(uefi_raw::protocol::console::serial::ControlBits::REQUEST_TO_SEND.bits() == 2);
assert!(uefi_raw::protocol::console::serial::ControlBits::HARDWARE_LOOPBACK_ENABLE.bits() == 4096);
assert!(uefi_raw::protocol::console::serial::ControlBits::SOFTWARE_LOOPBACK_ENABLE.bits() == 8192);
assert!(uefi_raw::protocol::console::serial::ControlBits::HARDWARE_FLOW_CONTROL_ENABLE.bits() == 16384);
assert!(uefi_raw::protocol::console::serial::ControlBits::SETTABLE.bits() == 28675);
assert!(uefi_raw::protocol::console::serial::SerialIoProtocolRevision::REVISION_1_0.0 == 65536);
assert!(uefi_raw::protocol::console::serial::SerialIoProtocolRevision::REVISION_1_1.0 == 65537);
assert!(uefi_raw::protocol::console::serial::Parity::DEFAULT.0 == 0);
assert!(uefi_raw::protocol::console::serial::Parity::NONE.0 == 1);
assert!(uefi_raw::protocol::console::serial::Parity::EVEN.0 == 2);
assert!(uefi_raw::protocol::console::serial::Parity::ODD.0 == 3);
assert!(uefi_raw::protocol::console::serial::Parity::MARK.0 == 4);
assert!(uefi_raw::protocol::console::serial::Parity::SPACE.0 == 5);
assert!(uefi_raw::protocol::console::serial::StopBits::DEFAULT.0 == 0);
assert!(uefi_raw::protocol::console::serial::StopBits::ONE.0 == 1);
assert!(uefi_raw::protocol::console::serial::StopBits::ONE_FIVE.0 == 2);
assert!(uefi_raw::protocol::console::serial::StopBits::TWO.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceType::HARDWARE.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceType::ACPI.0 == 2);
assert!(uefi_raw::protocol::device_path::DeviceType::MESSAGING.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceType::MEDIA.0 == 4);
assert!(uefi_raw::protocol::device_path::DeviceType::BIOS_BOOT_SPEC.0 == 5);
assert!(uefi_raw::protocol::device_path::DeviceType::END.0 == 127);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_PCI.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_PCCARD.0 == 2);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_MEMORY_MAPPED.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_VENDOR.0 == 4);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_CONTROLLER.0 == 5);
assert!(uefi_raw::protocol::device_path::DeviceSubType::HARDWARE_BMC.0 == 6);
assert!(uefi_raw::protocol::device_path::DeviceSubType::ACPI.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::ACPI_EXPANDED.0 == 2);
assert!(uefi_raw::protocol::device_path::DeviceSubType::ACPI_ADR.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceSubType::ACPI_NVDIMM.0 == 4);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_ATAPI.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_SCSI.0 == 2);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_FIBRE_CHANNEL.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_1394.0 == 4);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_USB.0 == 5);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_I2O.0 == 6);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_INFINIBAND.0 == 9);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_VENDOR.0 == 10);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_MAC_ADDRESS.0 == 11);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_IPV4.0 == 12);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_IPV6.0 == 13);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_UART.0 == 14);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_USB_CLASS.0 == 15);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_USB_WWID.0 == 16);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_DEVICE_LOGICAL_UNIT.0 == 17);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_SATA.0 == 18);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_ISCSI.0 == 19);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_VLAN.0 == 20);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_FIBRE_CHANNEL_EX.0 == 21);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_SCSI_SAS_EX.0 == 22);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_NVME_NAMESPACE.0 == 23);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_URI.0 == 24);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_UFS.0 == 25);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_SD.0 == 26);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_BLUETOOTH.0 == 27);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_WIFI.0 == 28);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_EMMC.0 == 29);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_BLUETOOTH_LE.0 == 30);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_DNS.0 == 31);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_NVDIMM_NAMESPACE.0 == 32);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_REST_SERVICE.0 == 33);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MESSAGING_NVME_OF_NAMESPACE.0 == 34);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_HARD_DRIVE.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_CD_ROM.0 == 2);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_VENDOR.0 == 3);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_FILE_PATH.0 == 4);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_PROTOCOL.0 == 5);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_PIWG_FIRMWARE_FILE.0 == 6);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_PIWG_FIRMWARE_VOLUME.0 == 7);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_RELATIVE_OFFSET_RANGE.0 == 8);
assert!(uefi_raw::protocol::device_path::DeviceSubType::MEDIA_RAM_DISK.0 == 9);
assert!(uefi_raw::protocol::device_path::DeviceSubType::BIOS_BOOT_SPECIFICATION.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::END_INSTANCE.0 == 1);
assert!(uefi_raw::protocol::device_path::DeviceSubType::END_ENTIRE.0 == 255);
assert!(uefi_raw::protocol::device_path::hardware::BmcInterfaceType::UNKNOWN.0 == 0);
assert!(uefi_raw::protocol::device_path::hardware::BmcInterfaceType::KEYBOARD_CONTROLLER_STYLE.0 == 1);
assert!(uefi_raw::protocol::device_path::hardware::BmcInterfaceType::SERVER_MANAGEMENT_INTERFACE_CHIP.0 == 2);
assert!(uefi_raw::protocol::device_path::hardware::BmcInterfaceType::BLOCK_TRANSFER.0 == 3);
assert!(uefi_raw::protocol::device_path::messaging::PrimarySecondary::PRIMARY.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::PrimarySecondary::SECONDARY.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::MasterSlave::MASTER.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::MasterSlave::SLAVE.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::Ipv4AddressOrigin::DHCP.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::Ipv4AddressOrigin::STATIC.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::Ipv6AddressOrigin::MANUAL.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::Ipv6AddressOrigin::STATELESS_AUTO_CONFIGURATION.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::Ipv6AddressOrigin::STATEFUL_CONFIGURATION.0 == 2);
assert!(uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags::SERVICE.bits() == 1);
assert!(uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags::EXTENDED_BOOT_ENVIRONMENT.bits() == 2);
assert!(uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags::CONSOLE_PROTOCOL.bits() == 4);
assert!(uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags::STORAGE_PROTOCOL.bits() == 8);
assert!(uefi_raw::protocol::device_path::messaging::InfinibandResourceFlags::NETWORK_PROTOCOL.bits() == 16);
assert!(uefi_raw::protocol::device_path::messaging::Parity::DEFAULT.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::Parity::NO.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::Parity::EVEN.0 == 2);
assert!(uefi_raw::protocol::device_path::messaging::Parity::ODD.0 == 3);
assert!(uefi_raw::protocol::device_path::messaging::Parity::MARK.0 == 4);
assert!(uefi_raw::protocol::device_path::messaging::Parity::SPACE.0 == 5);
assert!(uefi_raw::protocol::device_path::messaging::StopBits::DEFAULT.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::StopBits::ONE.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::StopBits::ONE_POINT_FIVE.0 == 2);
assert!(uefi_raw::protocol::device_path::messaging::StopBits::TWO.0 == 3);
assert!(uefi_raw::protocol::device_path::messaging::IscsiProtocol::TCP.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::IscsiLoginOptions::HEADER_DIGEST_USING_CRC32.bits() == 2);
assert!(uefi_raw::protocol::device_path::messaging::IscsiLoginOptions::DATA_DIGEST_USING_CRC32.bits() == 8);
assert!(uefi_raw::protocol::device_path::messaging::IscsiLoginOptions::AUTH_METHOD_NONE.bits() == 2048);
assert!(uefi_raw::protocol::device_path::messaging::IscsiLoginOptions::CHAP_UNI.bits() == 4096);
assert!(uefi_raw::protocol::device_path::messaging::BluetoothLeAddressType::PUBLIC.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::BluetoothLeAddressType::RANDOM.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::DnsAddressType::IPV4.0 == 0);
assert!(uefi_raw::protocol::device_path::messaging::DnsAddressType::IPV6.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::RestServiceType::REDFISH.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::RestServiceType::ODATA.0 == 2);
assert!(uefi_raw::protocol::device_path::messaging::RestServiceType::VENDOR.0 == 255);
assert!(uefi_raw::protocol::device_path::messaging::RestServiceAccessMode::IN_BAND.0 == 1);
assert!(uefi_raw::protocol::device_path::messaging::RestServiceAccessMode::OUT_OF_BAND.0 == 2);
assert!(uefi_raw::protocol::device_path::media::PartitionFormat::MBR.0 == 1);
assert!(uefi_raw::protocol::device_path::media::PartitionFormat::GPT.0 == 2);
{ let actual = (uefi_raw::protocol::console::AbsolutePointerProtocol::GUID).to_bytes(); let expected = [0x2b, 0xd3, 0x59, 0x8d, 0x55, 0xc6, 0xe9, 0x4a, 0x9b, 0x15, 0xf2, 0x59, 0x04, 0x99, 0x2a, 0x43]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::SimpleTextInputProtocol::GUID).to_bytes(); let expected = [0xc1, 0x77, 0x74, 0x38, 0xc7, 0x69, 0xd2, 0x11, 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::SimpleTextInputExProtocol::GUID).to_bytes(); let expected = [0x34, 0x75, 0x9e, 0xdd, 0x62, 0x77, 0x98, 0x46, 0x8c, 0x14, 0xf5, 0x85, 0x17, 0xa6, 0x25, 0xaa]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::SimpleTextOutputProtocol::GUID).to_bytes(); let expected = [0xc2, 0x77, 0x74, 0x38, 0xc7, 0x69, 0xd2, 0x11, 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::SimplePointerProtocol::GUID).to_bytes(); let expected = [0x87, 0x8c, 0x87, 0x31, 0x75, 0x0b, 0xd5, 0x11, 0x9a, 0x4f, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0x4d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::GraphicsOutputProtocol::GUID).to_bytes(); let expected = [0xde, 0xa9, 0x42, 0x90, 0xdc, 0x23, 0x38, 0x4a, 0x96, 0xfb, 0x7a, 0xde, 0xd0, 0x80, 0x51, 0x6a]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::EdidDiscoveredProtocol::GUID).to_bytes(); let expected = [0xf6, 0x34, 0x0c, 0x1c, 0x80, 0xd3, 0xfa, 0x41, 0xa0, 0x49, 0x8a, 0xd0, 0x6c, 0x1a, 0x66, 0xaa]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::serial::SerialIoProtocol::GUID).to_bytes(); let expected = [0x6f, 0xcf, 0x25, 0xbb, 0xd4, 0xf1, 0xd2, 0x11, 0x9a, 0x0c, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0xfd]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::console::serial::SerialIoProtocol_1_1::GUID).to_bytes(); let expected = [0x6f, 0xcf, 0x25, 0xbb, 0xd4, 0xf1, 0xd2, 0x11, 0x9a, 0x0c, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0xfd]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::loaded_image::LoadedImageProtocol::GUID).to_bytes(); let expected = [0xa1, 0x31, 0x1b, 0x5b, 0x62, 0x95, 0xd2, 0x11, 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::DevicePathProtocol::GUID).to_bytes(); let expected = [0x91, 0x6e, 0x57, 0x09, 0x3f, 0x6d, 0xd2, 0x11, 0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::DevicePathToTextProtocol::GUID).to_bytes(); let expected = [0x20, 0x3e, 0x84, 0x8b, 0x32, 0x81, 0x52, 0x48, 0x90, 0xcc, 0x55, 0x1a, 0x4e, 0x4a, 0x7f, 0x1c]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::DevicePathFromTextProtocol::GUID).to_bytes(); let expected = [0x21, 0x9a, 0xc9, 0x05, 0x0f, 0xc7, 0xd2, 0x4a, 0x8a, 0x5f, 0x35, 0xdf, 0x33, 0x43, 0xf5, 0x1e]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::DevicePathUtilitiesProtocol::GUID).to_bytes(); let expected = [0x4e, 0xbe, 0x79, 0x03, 0x06, 0xd7, 0x7d, 0x43, 0xb0, 0x37, 0xed, 0xb8, 0x2f, 0xb7, 0x72, 0xa4]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::media::RamDiskType::VIRTUAL_DISK.0).to_bytes(); let expected = [0x5a, 0x53, 0xab, 0x77, 0xfc, 0x45, 0x4b, 0x62, 0x55, 0x60, 0xf7, 0xb2, 0x81, 0xd1, 0xf9, 0x6e]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::media::RamDiskType::VIRTUAL_CD.0).to_bytes(); let expected = [0x30, 0xbd, 0x5a, 0x3d, 0x75, 0x41, 0xce, 0x87, 0x6d, 0x64, 0xd2, 0xad, 0xe5, 0x23, 0xc4, 0xbb]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::media::RamDiskType::PERSISTENT_VIRTUAL_DISK.0).to_bytes(); let expected = [0xc9, 0x02, 0xea, 0x5c, 0x07, 0x4d, 0xd3, 0x69, 0x26, 0x9f, 0x44, 0x96, 0xfb, 0xe0, 0x96, 0xf9]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::device_path::media::RamDiskType::PERSISTENT_VIRTUAL_CD.0).to_bytes(); let expected = [0x88, 0x81, 0x01, 0x08, 0xcd, 0x42, 0x48, 0xbb, 0x10, 0x0f, 0x53, 0x87, 0xd5, 0x3d, 0xed, 0x3d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::media::LoadFileProtocol::GUID).to_bytes(); let expected = [0x91, 0x30, 0xec, 0x56, 0x4c, 0x95, 0xd2, 0x11, 0x8e, 0x3f, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::media::LoadFile2Protocol::GUID).to_bytes(); let expected = [0xc1, 0xc0, 0x06, 0x40, 0xb3, 0xfc, 0x3e, 0x40, 0x99, 0x6d, 0x4a, 0x6c, 0x87, 0x24, 0xe0, 0x6d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::media::StorageSecurityCommandProtocol::GUID).to_bytes(); let expected = [0x6d, 0x0b, 0x8b, 0xc8, 0xfc, 0x0d, 0xa7, 0x49, 0x9c, 0xb4, 0x49, 0x07, 0x4b, 0x4c, 0x3a, 0x78]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = (uefi_raw::protocol::shell_params::ShellParametersProtocol::GUID).to_bytes(); let expected = [0x36, 0x31, 0x2f, 0x75, 0x16, 0x4e, 0xdc, 0x4f, 0xa2, 0x2a, 0xe5, 0xf4, 0x68, 0x12, 0xf4, 0xca]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
};
