#!/usr/bin/env python3
"""Deterministic semantic fixtures derived from pinned addr.rs cases and boundaries."""
import json
import sys
from pathlib import Path
HERE=Path(__file__).resolve().parent
def write(path, text):
    if '--check' in sys.argv:
        if not path.is_file() or path.read_text()!=text: raise SystemExit(f'generated fixture differs: {path}')
    else: path.write_text(text)
rows=[]
def add(group,call,expected,rust=None):
    rows.append(dict(group=group,call=call,expected=expected,rust=rust))
MAX=2**64-1; LOW=2**47-1; HIGH=2**64-2**47; PHY=2**52-1; DENSE=2**48-1
for x in [0,123,LOW,LOW+1,HIGH-1,HIGH,MAX]:
    add('canonical',f'virtual_check({x})',x if x<=LOW or x>=HIGH else None,f'VirtAddr::try_new({x}).ok().map(VirtAddr::as_u64)')
for x in [0,2**47,123,123<<47,MAX]:
    y=x&DENSE;y=y if y<=LOW else y|0xffff000000000000
    add('truncate',f'virtual_truncate({x})',y,f'Some(VirtAddr::new_truncate({x}).as_u64())')
for x in [0,PHY,PHY+1,MAX]:
    add('physical',f'physical_check({x}, 0)',x if x<=PHY else None,f'PhysAddr::try_new({x}).ok().map(PhysAddr::as_u64)')
    add('physical',f'physical_truncate({x}, 0)',x&PHY,f'Some(PhysAddr::new_truncate({x}).as_u64())')
for x,a in [(0,1),(1234,1),(MAX,1),(0,2),(1233,2),(MAX-1,2),(0,128),(0,2**63),(MAX,2),(1,0),(1,3)]:
    valid=a>0 and a&(a-1)==0;y=((x+a-1)//a)*a if valid else MAX+1
    add('alignment',f'align_up({x}, {a})',y if y<=MAX else None,f'caught(|| x86_64::align_up({x}, {a}))')
for x,a in [(1233,16),(MAX,2),(0,1),(123,0),(123,3)]:
    y=x&~(a-1) if a>0 and a&(a-1)==0 else None
    add('alignment',f'align_down({x}, {a})',y,f'caught(|| x86_64::align_down({x}, {a}))')
for x,a,up,e in [(LOW,2,True,HIGH),(HIGH,2**48,False,0),(MAX,2,True,None),(1233,2,True,1234)]:
    add('virtual_alignment',f'virtual_align({x}, {a}, {str(up).lower()})',e,f'caught(|| VirtAddr::new({x}).align_{"up" if up else "down"}({a}u64).as_u64())')
for x,a,up,e in [(PHY,2,True,None),(1233,16,False,1232)]:
    add('physical_alignment',f'physical_align({x}, {a}, {str(up).lower()}, 0)',e,f'caught(|| PhysAddr::new({x}).align_{"up" if up else "down"}({a}u64).as_u64())')
for physical in [False,True]:
    prefix='physical' if physical else 'virtual';typ='PhysAddr' if physical else 'VirtAddr';limit=PHY if physical else MAX
    for x,n,sub in [(limit,1,False),(0,1,True),(41,1,False),(41,1,True),(LOW,1,False),(HIGH,1,True),(PHY,0xffff000000000000,False)]:
        y=x-n if sub else x+n
        valid=x<=PHY and y<=PHY if physical else (x<=LOW or x>=HIGH) and (y<=LOW or y>=HIGH)
        e=y if valid and 0<=y<=MAX else None
        call=f'{prefix}_{"sub" if sub else "add"}({x}, {n}'+(', 0)' if physical else ')')
        add('arithmetic',call,e,f'caught(|| ({typ}::new({x}) {"-" if sub else "+"} {n}u64).as_u64())')
forward=[(0,0),(0,1),(LOW,1),(HIGH,1),(MAX,1),(LOW,0x123456789abd),(LOW,2**47),(LOW-255,2**47+255),(LOW-255,2**47+256),(LOW,2**47+1),(0,2**48)]
back=[(0,0),(0,1),(1,1),(HIGH,1),(HIGH+1,1),(0xffff923456789abc,0x123456789abd),(HIGH,2**47),(HIGH,0x7fffffffff01),(HIGH,2**47+1),(MAX,2**48)]
for backwards,values in [(False,forward),(True,back)]:
 for x,n in values:
    y=(x&DENSE)+(-n if backwards else n);e=None if not 0<=y<=DENSE else (y if y<=LOW else y|0xffff000000000000)
    add('stepping',f'virtual_step({x}, {n}, {str(backwards).lower()})',e,f'Step::{"backward" if backwards else "forward"}_checked(VirtAddr::new({x}), {n}).map(VirtAddr::as_u64)')
for a,b in [(0,0),(0,1),(1,0),(LOW,HIGH),(HIGH,LOW),(HIGH,HIGH),(HIGH,HIGH+1),(HIGH+1,HIGH),(0,2**32),(0,MAX)]:
    add('distance',f'virtual_steps_between({a}, {b})',(b&DENSE)-(a&DENSE) if b>=a else None,f'Step::steps_between(&VirtAddr::new({a}), &VirtAddr::new({b})).1.map(|n| n as u64)')
for x in [0,0x123456789abc,MAX]:
 for level in range(1,5):
    add('indices',f'page_index({x}, {level})',(x>>(12+9*(level-1)))&511,f'Some(u64::from(VirtAddr::new({x}).p{level}_index()))')
 add('indices',f'page_offset({x})',x&4095,f'Some(u64::from(VirtAddr::new({x}).page_offset()))')
for call,e in [('page_index(0, 0)',None),('page_index(0, 5)',None),('page_offset(140737488355328)',None),('physical_check(4096, 4096)',None),('physical_truncate(12288, 4096)',8192),('physical_check(0, 3)',None),('physical_truncate(0, 3)',None),('physical_truncate(0, 4503599627370496)',None)]:
    add('added_validation',call,e)
header='''// SPDX-License-Identifier: MIT OR Apache-2.0
// Modified addr.rs test scenarios; generated by generate.py, with added boundaries.
use x86::addresses;
use x86::addresses::NumberResult;
use extras;
machine equal(result: NumberResult, expected: u64) -> bool {
    transition result { NumberResult::Value { value } -> (value == expected) _ -> (false) }
}
machine rejected(result: NumberResult) -> bool { result in NumberResult::Rejected }
'''
parts=[header];groups=[]
for start in range(0,len(rows),8):
 name=f'group_{start}';groups.append(name);parts.append(f'machine {name}() -> bool {{')
 for i,row in enumerate(rows[start:start+8],start):
    call=row['call'];exp=row['expected'];raw=call.startswith('virtual_truncate(')
    parts.append(f'    let result{i}: {"u64" if raw else "NumberResult"} = addresses::{call};')
    predicate=f'result{i} == {exp}' if raw else f'rejected(result{i})' if exp is None else f'equal(result{i}, {exp})'
    parts.append(f'    let passed{i}: bool = {predicate};')
 parts.append('    '+' && '.join(f'passed{i}' for i in range(start,min(start+8,len(rows))))+'\n}')
parts.append('machine test_result() -> i32 {\n    let extra_ok: bool = extras::run();')
for name in groups:parts.append(f'    let {name}_ok: bool = {name}();')
parts.append('    transition extra_ok && '+' && '.join(g+'_ok' for g in groups)+' { true -> (0) _ -> (1) }\n}')
parts.append('const TEST_RESULT: i32 = test_result();\nmachine require_success(value: i32) requires value == 0; {}\ndata Main {}\nmachine Main::main(&mut self) { require_success(TEST_RESULT); }\n')
write(HERE/'main.omg', '\n'.join(parts))
write(HERE/'vectors.json', json.dumps({'scope':'expected numeric results, not ABI observations','cases':rows},indent=2)+'\n')
rust=['#![feature(step_trait)]','use x86_64::{VirtAddr, PhysAddr};','use core::iter::Step;','fn caught(f: impl FnOnce() -> u64 + std::panic::UnwindSafe) -> Option<u64> { std::panic::catch_unwind(f).ok() }','fn main() {','std::panic::set_hook(Box::new(|_| {}));']
for i,row in enumerate(rows):
 if row['rust']:
    expected='None' if row['expected'] is None else f'Some({row["expected"]}u64)'
    rust.append(f'assert_eq!({row["rust"]}, {expected}, "case {i}: {row["call"]}");')
rust.append(f'println!("{sum(bool(r["rust"]) for r in rows)} pinned Rust address witnesses passed");\n}}\n')
(HERE/'src').mkdir(exist_ok=True);write(HERE/'src/main.rs', '\n'.join(rust))
print(f'{len(rows)} Omega cases, {sum(bool(r["rust"]) for r in rows)} pinned Rust witnesses generated')
