#![no_std]
use core::mem::{size_of,align_of,offset_of};
use x86_64::structures::idt::*;
const _: () = assert!((PageFaultErrorCode::PROTECTION_VIOLATION.bits()) as u64 == 1);
const _: () = assert!((PageFaultErrorCode::CAUSED_BY_WRITE.bits()) as u64 == 2);
const _: () = assert!((PageFaultErrorCode::USER_MODE.bits()) as u64 == 4);
const _: () = assert!((PageFaultErrorCode::MALFORMED_TABLE.bits()) as u64 == 8);
const _: () = assert!((PageFaultErrorCode::INSTRUCTION_FETCH.bits()) as u64 == 16);
const _: () = assert!((PageFaultErrorCode::PROTECTION_KEY.bits()) as u64 == 32);
const _: () = assert!((PageFaultErrorCode::SHADOW_STACK.bits()) as u64 == 64);
const _: () = assert!((PageFaultErrorCode::HLAT.bits()) as u64 == 128);
const _: () = assert!((PageFaultErrorCode::SGX.bits()) as u64 == 32768);
const _: () = assert!((PageFaultErrorCode::RMP.bits()) as u64 == 2147483648);
const _: () = assert!((ExceptionVector::Division as u8) as u64 == 0);
const _: () = assert!((ExceptionVector::Debug as u8) as u64 == 1);
const _: () = assert!((ExceptionVector::NonMaskableInterrupt as u8) as u64 == 2);
const _: () = assert!((ExceptionVector::Breakpoint as u8) as u64 == 3);
const _: () = assert!((ExceptionVector::Overflow as u8) as u64 == 4);
const _: () = assert!((ExceptionVector::BoundRange as u8) as u64 == 5);
const _: () = assert!((ExceptionVector::InvalidOpcode as u8) as u64 == 6);
const _: () = assert!((ExceptionVector::DeviceNotAvailable as u8) as u64 == 7);
const _: () = assert!((ExceptionVector::Double as u8) as u64 == 8);
const _: () = assert!((ExceptionVector::InvalidTss as u8) as u64 == 10);
const _: () = assert!((ExceptionVector::SegmentNotPresent as u8) as u64 == 11);
const _: () = assert!((ExceptionVector::Stack as u8) as u64 == 12);
const _: () = assert!((ExceptionVector::GeneralProtection as u8) as u64 == 13);
const _: () = assert!((ExceptionVector::Page as u8) as u64 == 14);
const _: () = assert!((ExceptionVector::X87FloatingPoint as u8) as u64 == 16);
const _: () = assert!((ExceptionVector::AlignmentCheck as u8) as u64 == 17);
const _: () = assert!((ExceptionVector::MachineCheck as u8) as u64 == 18);
const _: () = assert!((ExceptionVector::SimdFloatingPoint as u8) as u64 == 19);
const _: () = assert!((ExceptionVector::Virtualization as u8) as u64 == 20);
const _: () = assert!((ExceptionVector::ControlProtection as u8) as u64 == 21);
const _: () = assert!((ExceptionVector::HypervisorInjection as u8) as u64 == 28);
const _: () = assert!((ExceptionVector::VmmCommunication as u8) as u64 == 29);
const _: () = assert!((ExceptionVector::Security as u8) as u64 == 30);
const _: () = assert!((size_of::<Entry<HandlerFunc>>()) as u64 == 16);
const _: () = assert!((align_of::<Entry<HandlerFunc>>()) as u64 == 4);
const _: () = assert!((size_of::<EntryOptions>()) as u64 == 4);
const _: () = assert!((align_of::<EntryOptions>()) as u64 == 2);
const _: () = assert!((size_of::<InterruptDescriptorTable>()) as u64 == 4096);
const _: () = assert!((align_of::<InterruptDescriptorTable>()) as u64 == 16);
const _: () = assert!((size_of::<InterruptStackFrameValue>()) as u64 == 40);
const _: () = assert!((align_of::<InterruptStackFrameValue>()) as u64 == 8);
const _: () = assert!((size_of::<InterruptStackFrame>()) as u64 == 40);
const _: () = assert!((align_of::<InterruptStackFrame>()) as u64 == 8);
const _: () = assert!((size_of::<PageFaultErrorCode>()) as u64 == 8);
const _: () = assert!((align_of::<PageFaultErrorCode>()) as u64 == 8);
const _: () = assert!((offset_of!(InterruptStackFrameValue, instruction_pointer)) as u64 == 0);
const _: () = assert!((offset_of!(InterruptStackFrameValue, code_segment)) as u64 == 8);
const _: () = assert!((offset_of!(InterruptStackFrameValue, cpu_flags)) as u64 == 16);
const _: () = assert!((offset_of!(InterruptStackFrameValue, stack_pointer)) as u64 == 24);
const _: () = assert!((offset_of!(InterruptStackFrameValue, stack_segment)) as u64 == 32);
const _: () = assert!((offset_of!(InterruptDescriptorTable, divide_error)) as u64 == 0);
const _: () = assert!((offset_of!(InterruptDescriptorTable, debug)) as u64 == 16);
const _: () = assert!((offset_of!(InterruptDescriptorTable, non_maskable_interrupt)) as u64 == 32);
const _: () = assert!((offset_of!(InterruptDescriptorTable, breakpoint)) as u64 == 48);
const _: () = assert!((offset_of!(InterruptDescriptorTable, overflow)) as u64 == 64);
const _: () = assert!((offset_of!(InterruptDescriptorTable, bound_range_exceeded)) as u64 == 80);
const _: () = assert!((offset_of!(InterruptDescriptorTable, invalid_opcode)) as u64 == 96);
const _: () = assert!((offset_of!(InterruptDescriptorTable, device_not_available)) as u64 == 112);
const _: () = assert!((offset_of!(InterruptDescriptorTable, double_fault)) as u64 == 128);
const _: () = assert!((offset_of!(InterruptDescriptorTable, invalid_tss)) as u64 == 160);
const _: () = assert!((offset_of!(InterruptDescriptorTable, segment_not_present)) as u64 == 176);
const _: () = assert!((offset_of!(InterruptDescriptorTable, stack_segment_fault)) as u64 == 192);
const _: () = assert!((offset_of!(InterruptDescriptorTable, general_protection_fault)) as u64 == 208);
const _: () = assert!((offset_of!(InterruptDescriptorTable, page_fault)) as u64 == 224);
const _: () = assert!((offset_of!(InterruptDescriptorTable, x87_floating_point)) as u64 == 256);
const _: () = assert!((offset_of!(InterruptDescriptorTable, alignment_check)) as u64 == 272);
const _: () = assert!((offset_of!(InterruptDescriptorTable, machine_check)) as u64 == 288);
const _: () = assert!((offset_of!(InterruptDescriptorTable, simd_floating_point)) as u64 == 304);
const _: () = assert!((offset_of!(InterruptDescriptorTable, virtualization)) as u64 == 320);
const _: () = assert!((offset_of!(InterruptDescriptorTable, cp_protection_exception)) as u64 == 336);
const _: () = assert!((offset_of!(InterruptDescriptorTable, hv_injection_exception)) as u64 == 448);
const _: () = assert!((offset_of!(InterruptDescriptorTable, vmm_communication_exception)) as u64 == 464);
const _: () = assert!((offset_of!(InterruptDescriptorTable, security_exception)) as u64 == 480);
