#![no_std]
// SPDX-License-Identifier: MIT OR Apache-2.0
// Cross-target assertions of independently measured pinned Rust; not Omega execution.
use core::mem::{size_of,align_of,offset_of};
const _: () = {
assert!(offset_of!(uefi_raw::Ipv4Address, 0) == 0);
assert!(size_of::<uefi_raw::Ipv4Address>() == 4);
assert!(align_of::<uefi_raw::Ipv4Address>() == 1);
assert!(offset_of!(uefi_raw::Ipv6Address, 0) == 0);
assert!(size_of::<uefi_raw::Ipv6Address>() == 16);
assert!(align_of::<uefi_raw::Ipv6Address>() == 1);
assert!(offset_of!(uefi_raw::IpAddress, addr) == 0);
assert!(offset_of!(uefi_raw::IpAddress, v4) == 0);
assert!(offset_of!(uefi_raw::IpAddress, v6) == 0);
assert!(size_of::<uefi_raw::IpAddress>() == 16);
assert!(align_of::<uefi_raw::IpAddress>() == 4);
assert!(offset_of!(uefi_raw::MacAddress, 0) == 0);
assert!(size_of::<uefi_raw::MacAddress>() == 32);
assert!(align_of::<uefi_raw::MacAddress>() == 1);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Event>() == 4);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Event>() == 4);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4State>() == 4);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4State>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Packet, size) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Packet, length) == 4);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Packet, header) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Packet, magik) == 244);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Packet, option) == 248);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Packet>() == 248);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Packet>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, op_code) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, hw_type) == 1);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, hw_addr_len) == 2);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, hops) == 3);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, xid) == 4);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, seconds) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, reserved) == 10);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, client_addr) == 12);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, your_addr) == 16);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, server_addr) == 20);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, gateway_addr) == 24);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, client_hw_addr) == 28);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, server_name) == 44);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Header, boot_file_name) == 108);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Header>() == 236);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Header>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4PacketOption, op_code) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4PacketOption, length) == 1);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4PacketOption, data) == 2);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4PacketOption>() == 2);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4PacketOption>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, discover_try_count) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, discover_timeout) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, request_try_count) == 16);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, request_timeout) == 24);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, client_address) == 32);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, callback) == 40);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, callback_context) == 48);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, option_count) == 56);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData, option_list) == 64);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData>() == 72);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ConfigData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, state) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, config_data) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, client_address) == 80);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, client_mac_address) == 84);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, server_address) == 116);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, router_address) == 120);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, subnet_mask) == 124);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, lease_time) == 128);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ModeData, reply_packet) == 136);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ModeData>() == 144);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ModeData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ListenPoint, listen_address) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ListenPoint, subnet_mask) == 4);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4ListenPoint, listen_port) == 8);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ListenPoint>() == 10);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4ListenPoint>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, status) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, completion_event) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, remote_address) == 16);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, remote_port) == 20);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, gateway_address) == 22);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, listen_point_count) == 28);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, listen_points) == 32);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, timeout_value) == 40);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, packet) == 48);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, response_count) == 56);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken, response_list) == 64);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken>() == 72);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4TransmitReceiveToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, get_mode_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, configure) == 8);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, start) == 16);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, renew_rebind) == 24);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, release) == 32);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, stop) == 40);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, build) == 48);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, transmit_receive) == 56);
assert!(offset_of!(uefi_raw::protocol::network::dhcp4::Dhcp4Protocol, parse) == 64);
assert!(size_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Protocol>() == 72);
assert!(align_of::<uefi_raw::protocol::network::dhcp4::Dhcp4Protocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpConfigData, http_version) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpConfigData, time_out_millisec) == 4);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpConfigData, local_addr_is_ipv6) == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpConfigData, access_point) == 16);
assert!(size_of::<uefi_raw::protocol::network::http::HttpConfigData>() == 24);
assert!(align_of::<uefi_raw::protocol::network::http::HttpConfigData>() == 8);
assert!(size_of::<uefi_raw::protocol::network::http::HttpVersion>() == 4);
assert!(align_of::<uefi_raw::protocol::network::http::HttpVersion>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV4AccessPoint, use_default_addr) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV4AccessPoint, local_address) == 1);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV4AccessPoint, local_subnet) == 5);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV4AccessPoint, local_port) == 10);
assert!(size_of::<uefi_raw::protocol::network::http::HttpV4AccessPoint>() == 12);
assert!(align_of::<uefi_raw::protocol::network::http::HttpV4AccessPoint>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV6AccessPoint, local_address) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpV6AccessPoint, local_port) == 16);
assert!(size_of::<uefi_raw::protocol::network::http::HttpV6AccessPoint>() == 18);
assert!(align_of::<uefi_raw::protocol::network::http::HttpV6AccessPoint>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpAccessPoint, ipv4_node) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpAccessPoint, ipv6_node) == 0);
assert!(size_of::<uefi_raw::protocol::network::http::HttpAccessPoint>() == 8);
assert!(align_of::<uefi_raw::protocol::network::http::HttpAccessPoint>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpToken, event) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpToken, status) == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpToken, message) == 16);
assert!(size_of::<uefi_raw::protocol::network::http::HttpToken>() == 24);
assert!(align_of::<uefi_raw::protocol::network::http::HttpToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpMessage, data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpMessage, header_count) == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpMessage, header) == 16);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpMessage, body_length) == 24);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpMessage, body) == 32);
assert!(size_of::<uefi_raw::protocol::network::http::HttpMessage>() == 40);
assert!(align_of::<uefi_raw::protocol::network::http::HttpMessage>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpRequestData, method) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpRequestData, url) == 8);
assert!(size_of::<uefi_raw::protocol::network::http::HttpRequestData>() == 16);
assert!(align_of::<uefi_raw::protocol::network::http::HttpRequestData>() == 8);
assert!(size_of::<uefi_raw::protocol::network::http::HttpMethod>() == 4);
assert!(align_of::<uefi_raw::protocol::network::http::HttpMethod>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpResponseData, status_code) == 0);
assert!(size_of::<uefi_raw::protocol::network::http::HttpResponseData>() == 4);
assert!(align_of::<uefi_raw::protocol::network::http::HttpResponseData>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpRequestOrResponse, request) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpRequestOrResponse, response) == 0);
assert!(size_of::<uefi_raw::protocol::network::http::HttpRequestOrResponse>() == 8);
assert!(align_of::<uefi_raw::protocol::network::http::HttpRequestOrResponse>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpHeader, field_name) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpHeader, field_value) == 8);
assert!(size_of::<uefi_raw::protocol::network::http::HttpHeader>() == 16);
assert!(align_of::<uefi_raw::protocol::network::http::HttpHeader>() == 8);
assert!(size_of::<uefi_raw::protocol::network::http::HttpStatusCode>() == 4);
assert!(align_of::<uefi_raw::protocol::network::http::HttpStatusCode>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, get_mode_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, configure) == 8);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, request) == 16);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, cancel) == 24);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, response) == 32);
assert!(offset_of!(uefi_raw::protocol::network::http::HttpProtocol, poll) == 40);
assert!(size_of::<uefi_raw::protocol::network::http::HttpProtocol>() == 48);
assert!(align_of::<uefi_raw::protocol::network::http::HttpProtocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4RouteTable, subnet_addr) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4RouteTable, subnet_mask) == 4);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4RouteTable, gateway_addr) == 8);
assert!(size_of::<uefi_raw::protocol::network::ip4::Ip4RouteTable>() == 12);
assert!(align_of::<uefi_raw::protocol::network::ip4::Ip4RouteTable>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, is_started) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, max_packet_size) == 4);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, config_data) == 8);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, is_configured) == 36);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, group_count) == 40);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, group_table) == 48);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, route_count) == 56);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, route_table) == 64);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, icmp_type_count) == 72);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ModeData, icmp_type_list) == 80);
assert!(size_of::<uefi_raw::protocol::network::ip4::Ip4ModeData>() == 88);
assert!(align_of::<uefi_raw::protocol::network::ip4::Ip4ModeData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4IcmpType, type_) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4IcmpType, code) == 1);
assert!(size_of::<uefi_raw::protocol::network::ip4::Ip4IcmpType>() == 2);
assert!(align_of::<uefi_raw::protocol::network::ip4::Ip4IcmpType>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, default_protocol) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, accept_any_protocol) == 1);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, accept_icmp_errors) == 2);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, accept_broadcast) == 3);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, accept_promiscuous) == 4);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, use_default_address) == 5);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, station_address) == 6);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, subnet_mask) == 10);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, type_of_service) == 14);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, time_to_live) == 15);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, do_not_fragment) == 16);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, raw_data) == 17);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, receive_timeout) == 20);
assert!(offset_of!(uefi_raw::protocol::network::ip4::Ip4ConfigData, transmit_timeout) == 24);
assert!(size_of::<uefi_raw::protocol::network::ip4::Ip4ConfigData>() == 28);
assert!(align_of::<uefi_raw::protocol::network::ip4::Ip4ConfigData>() == 4);
assert!(size_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType>() == 4);
assert!(align_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, name) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, if_type) == 64);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, hw_addr_size) == 68);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, hw_addr) == 72);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, station_addr) == 104);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, subnet_mask) == 108);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, route_table_size) == 112);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo, route_table) == 120);
assert!(size_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo>() == 128);
assert!(align_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2InterfaceInfo>() == 8);
assert!(size_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2Policy>() == 4);
assert!(align_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2Policy>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2ManualAddress, address) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2ManualAddress, subnet_mask) == 4);
assert!(size_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2ManualAddress>() == 8);
assert!(align_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2ManualAddress>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol, set_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol, get_data) == 8);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol, register_data_notify) == 16);
assert!(offset_of!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol, unregister_data_notify) == 24);
assert!(size_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol>() == 32);
assert!(align_of::<uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, revision) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, start) == 8);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, stop) == 16);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, dhcp) == 24);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, discover) == 32);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, mtftp) == 40);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, udp_write) == 48);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, udp_read) == 56);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, set_ip_filter) == 64);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, arp) == 72);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, set_parameters) == 80);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, set_station_ip) == 88);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, set_packets) == 96);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol, mode) == 104);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol>() == 112);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol>() == 8);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeBootType>() == 2);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeBootType>() == 2);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode>() == 4);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, use_m_cast) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, use_b_cast) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, use_u_cast) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, must_use_list) == 3);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, server_m_cast_ip) == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, ip_cnt) == 20);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo, srv_list) == 24);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo>() == 24);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDiscoverInfo>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist, server_type) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist, accept_any_response) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist, reserved) == 3);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist, ip_addr) == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist>() == 20);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeSrvlist>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo, m_cast_ip) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo, c_port) == 16);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo, s_port) == 18);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo, listen_timeout) == 20);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo, transmit_timeout) == 22);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo>() == 24);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeMtftpInfo>() == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags>() == 2);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, started) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, ipv6_available) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, ipv6_supported) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, using_ipv6) == 3);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, bis_supported) == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, bis_detected) == 5);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, auto_arp) == 6);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, send_guid) == 7);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, dhcp_discover_valid) == 8);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, dhcp_ack_received) == 9);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, proxy_offer_received) == 10);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_discover_valid) == 11);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_reply_received) == 12);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_bis_reply_received) == 13);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, icmp_error_received) == 14);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, tftp_error_received) == 15);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, make_callbacks) == 16);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, ttl) == 17);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, tos) == 18);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, station_ip) == 20);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, subnet_mask) == 36);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, dhcp_discover) == 52);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, dhcp_ack) == 1524);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, proxy_offer) == 2996);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_discover) == 4468);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_reply) == 5940);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, pxe_bis_reply) == 7412);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, ip_filter) == 8884);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, arp_cache_entries) == 9016);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, arp_cache) == 9020);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, route_table_entries) == 9404);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, route_table) == 9408);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, icmp_error) == 9792);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeMode, tftp_error) == 10296);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeMode>() == 10424);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeMode>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodePacket, raw) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodePacket, dhcpv4) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodePacket, dhcpv6) == 0);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodePacket>() == 1472);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodePacket>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_opcode) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_hw_type) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_hw_addr_len) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_gate_hops) == 3);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_ident) == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_seconds) == 8);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_flags) == 10);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_ci_addr) == 12);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_yi_addr) == 16);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_si_addr) == 20);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_gi_addr) == 24);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_hw_addr) == 28);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_srv_name) == 44);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, bootp_boot_file) == 108);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, dhcp_magik) == 236);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet, dhcp_options) == 240);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet>() == 296);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet>() == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Flags>() == 2);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Flags>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV6Packet, message_type) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV6Packet, transaction_id) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV6Packet, dhcp_options) == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV6Packet>() == 1028);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV6Packet>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter, filters) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter, ip_cnt) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter, reserved) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter, ip_list) == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter>() == 132);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilter>() == 4);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags>() == 1);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeArpEntry, ip_addr) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeArpEntry, mac_addr) == 16);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeArpEntry>() == 48);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeArpEntry>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeRouteEntry, ip_addr) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeRouteEntry, subnet_mask) == 16);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeRouteEntry, gw_addr) == 32);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeRouteEntry>() == 48);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeRouteEntry>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError, ty) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError, code) == 1);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError, checksum) == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError, u) == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError, data) == 8);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError>() == 504);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpError>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion, reserved) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion, mtu) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion, pointer) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion, echo) == 0);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion>() == 4);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorUnion>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorEcho, identifier) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorEcho, sequence) == 2);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorEcho>() == 4);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeIcmpErrorEcho>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpError, error_code) == 0);
assert!(offset_of!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpError, error_string) == 1);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeTftpError>() == 128);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeTftpError>() == 1);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, revision) == 0);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, start) == 8);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, stop) == 16);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, initialize) == 24);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, reset) == 32);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, shutdown) == 40);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, receive_filters) == 48);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, station_address) == 56);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, statistics) == 64);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, multicast_ip_to_mac) == 72);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, non_volatile_data) == 80);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, get_status) == 88);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, transmit) == 96);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, receive) == 104);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, wait_for_packet) == 112);
assert!(offset_of!(uefi_raw::protocol::network::snp::SimpleNetworkProtocol, mode) == 120);
assert!(size_of::<uefi_raw::protocol::network::snp::SimpleNetworkProtocol>() == 128);
assert!(align_of::<uefi_raw::protocol::network::snp::SimpleNetworkProtocol>() == 8);
assert!(size_of::<uefi_raw::protocol::network::snp::ReceiveFlags>() == 4);
assert!(align_of::<uefi_raw::protocol::network::snp::ReceiveFlags>() == 4);
assert!(size_of::<uefi_raw::protocol::network::snp::InterruptStatus>() == 4);
assert!(align_of::<uefi_raw::protocol::network::snp::InterruptStatus>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_total_frames) == 0);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_good_frames) == 8);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_undersize_frames) == 16);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_oversize_frames) == 24);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_dropped_frames) == 32);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_unicast_frames) == 40);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_broadcast_frames) == 48);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_multicast_frames) == 56);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_crc_error_frames) == 64);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_total_bytes) == 72);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_total_frames) == 80);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_good_frames) == 88);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_undersize_frames) == 96);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_oversize_frames) == 104);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_dropped_frames) == 112);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_unicast_frames) == 120);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_broadcast_frames) == 128);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_multicast_frames) == 136);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_crc_error_frames) == 144);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_total_bytes) == 152);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, collisions) == 160);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, unsupported_protocol) == 168);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_duplicated_frames) == 176);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, rx_decrypt_error_frames) == 184);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_error_frames) == 192);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkStatistics, tx_retry_frames) == 200);
assert!(size_of::<uefi_raw::protocol::network::snp::NetworkStatistics>() == 208);
assert!(align_of::<uefi_raw::protocol::network::snp::NetworkStatistics>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, state) == 0);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, hw_address_size) == 4);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, media_header_size) == 8);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, max_packet_size) == 12);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, nv_ram_size) == 16);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, nv_ram_access_size) == 20);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, receive_filter_mask) == 24);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, receive_filter_setting) == 28);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, max_mcast_filter_count) == 32);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, mcast_filter_count) == 36);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, mcast_filter) == 40);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, current_address) == 552);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, broadcast_address) == 584);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, permanent_address) == 616);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, if_type) == 648);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, mac_address_changeable) == 649);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, multiple_tx_supported) == 650);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, media_present_supported) == 651);
assert!(offset_of!(uefi_raw::protocol::network::snp::NetworkMode, media_present) == 652);
assert!(size_of::<uefi_raw::protocol::network::snp::NetworkMode>() == 656);
assert!(align_of::<uefi_raw::protocol::network::snp::NetworkMode>() == 4);
assert!(size_of::<uefi_raw::protocol::network::snp::NetworkState>() == 4);
assert!(align_of::<uefi_raw::protocol::network::snp::NetworkState>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, get_mode_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, configure) == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, routes) == 16);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, connect) == 24);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, accept) == 32);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, transmit) == 40);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, receive) == 48);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, close) == 56);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, cancel) == 64);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Protocol, poll) == 72);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4Protocol>() == 80);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4Protocol>() == 8);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ConnectionState>() == 4);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ConnectionState>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ConfigData, type_of_service) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ConfigData, time_to_live) == 1);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ConfigData, access_point) == 2);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ConfigData, control_option) == 24);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ConfigData>() == 32);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ConfigData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, use_default_address) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, station_address) == 1);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, subnet_mask) == 5);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, station_port) == 10);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, remote_address) == 12);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, remote_port) == 16);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4AccessPoint, active_flag) == 18);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4AccessPoint>() == 20);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4AccessPoint>() == 2);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, receive_buffer_size) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, send_buffer_size) == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, max_syn_back_log) == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, connection_timeout) == 12);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, data_retries) == 16);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, fin_timeout) == 20);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, time_wait_timeout) == 24);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, keep_alive_probes) == 28);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, keep_alive_time) == 32);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, keep_alive_interval) == 36);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, enable_nagle) == 40);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, enable_time_stamp) == 41);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, enable_window_scaling) == 42);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, enable_selective_ack) == 43);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Option, enable_path_mtu_discovery) == 44);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4Option>() == 48);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4Option>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4CompletionToken, event) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4CompletionToken, status) == 8);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4CompletionToken>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4CompletionToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionToken, completion_token) == 0);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ConnectionToken>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ConnectionToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ListenToken, completion_token) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ListenToken, new_child_handle) == 16);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ListenToken>() == 24);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ListenToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4IoToken, completion_token) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4IoToken, packet) == 16);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4IoToken>() == 24);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4IoToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4CloseToken, completion_token) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4CloseToken, abort_on_close) == 16);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4CloseToken>() == 24);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4CloseToken>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Packet, rx_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4Packet, tx_data) == 0);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4Packet>() == 8);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4Packet>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4FragmentData, fragment_length) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4FragmentData, fragment_buf) == 8);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4FragmentData>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4FragmentData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ReceiveData, urgent) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ReceiveData, data_length) == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ReceiveData, fragment_count) == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ReceiveData, fragment_table) == 16);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ReceiveData>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ReceiveData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4TransmitData, push) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4TransmitData, urgent) == 1);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4TransmitData, data_length) == 4);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4TransmitData, fragment_count) == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4TransmitData, fragment_table) == 16);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4TransmitData>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4TransmitData>() == 8);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ClientConnectionModeParams, remote_ip) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tcp4::Tcp4ClientConnectionModeParams, remote_port) == 4);
assert!(size_of::<uefi_raw::protocol::network::tcp4::Tcp4ClientConnectionModeParams>() == 6);
assert!(align_of::<uefi_raw::protocol::network::tcp4::Tcp4ClientConnectionModeParams>() == 2);
assert!(size_of::<uefi_raw::protocol::network::tls::TlsConfigDataType>() == 4);
assert!(align_of::<uefi_raw::protocol::network::tls::TlsConfigDataType>() == 4);
assert!(offset_of!(uefi_raw::protocol::network::tls::TlsConfigurationProtocol, set_data) == 0);
assert!(offset_of!(uefi_raw::protocol::network::tls::TlsConfigurationProtocol, get_data) == 8);
assert!(size_of::<uefi_raw::protocol::network::tls::TlsConfigurationProtocol>() == 16);
assert!(align_of::<uefi_raw::protocol::network::tls::TlsConfigurationProtocol>() == 8);
assert!(size_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeUdpPort>() == 2);
assert!(align_of::<uefi_raw::protocol::network::pxe::PxeBaseCodeUdpPort>() == 2);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::SEND_DISCOVER.0 == 1);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::RCVD_OFFER.0 == 2);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::SELECT_OFFER.0 == 3);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::SEND_REQUEST.0 == 4);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::RCVD_ACK.0 == 5);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::RCVD_NAK.0 == 6);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::SEND_DECLINE.0 == 7);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::BOUND_COMPLETED.0 == 8);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::ENTER_RENEWING.0 == 9);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::ENTER_REBINDING.0 == 10);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::ADDRESS_LOST.0 == 11);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4Event::FAIL.0 == 12);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::STOPPED.0 == 0);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::INIT.0 == 1);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::SELECTING.0 == 2);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::REQUESTING.0 == 3);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::BOUND.0 == 4);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::RENEWING.0 == 5);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::REBINDING.0 == 6);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::INIT_REBOOT.0 == 7);
assert!(uefi_raw::protocol::network::dhcp4::Dhcp4State::REBOOTING.0 == 8);
assert!(uefi_raw::protocol::network::http::HttpVersion::HTTP_VERSION_10.0 == 0);
assert!(uefi_raw::protocol::network::http::HttpVersion::HTTP_VERSION_11.0 == 1);
assert!(uefi_raw::protocol::network::http::HttpVersion::HTTP_VERSION_UNSUPPORTED.0 == 2);
assert!(uefi_raw::protocol::network::http::HttpMethod::GET.0 == 0);
assert!(uefi_raw::protocol::network::http::HttpMethod::POST.0 == 1);
assert!(uefi_raw::protocol::network::http::HttpMethod::PATCH.0 == 2);
assert!(uefi_raw::protocol::network::http::HttpMethod::OPTIONS.0 == 3);
assert!(uefi_raw::protocol::network::http::HttpMethod::CONNECT.0 == 4);
assert!(uefi_raw::protocol::network::http::HttpMethod::HEAD.0 == 5);
assert!(uefi_raw::protocol::network::http::HttpMethod::PUT.0 == 6);
assert!(uefi_raw::protocol::network::http::HttpMethod::DELETE.0 == 7);
assert!(uefi_raw::protocol::network::http::HttpMethod::TRACE.0 == 8);
assert!(uefi_raw::protocol::network::http::HttpMethod::MAX.0 == 9);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_UNSUPPORTED.0 == 0);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_100_CONTINUE.0 == 1);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_101_SWITCHING_PROTOCOLS.0 == 2);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_200_OK.0 == 3);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_201_CREATED.0 == 4);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_202_ACCEPTED.0 == 5);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_203_NON_AUTHORITATIVE_INFORMATION.0 == 6);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_204_NO_CONTENT.0 == 7);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_205_RESET_CONTENT.0 == 8);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_206_PARTIAL_CONTENT.0 == 9);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_300_MULTIPLE_CHOICES.0 == 10);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_301_MOVED_PERMANENTLY.0 == 11);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_302_FOUND.0 == 12);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_303_SEE_OTHER.0 == 13);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_304_NOT_MODIFIED.0 == 14);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_305_USE_PROXY.0 == 15);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_307_TEMPORARY_REDIRECT.0 == 16);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_400_BAD_REQUEST.0 == 17);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_401_UNAUTHORIZED.0 == 18);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_402_PAYMENT_REQUIRED.0 == 19);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_403_FORBIDDEN.0 == 20);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_404_NOT_FOUND.0 == 21);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_405_METHOD_NOT_ALLOWED.0 == 22);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_406_NOT_ACCEPTABLE.0 == 23);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_407_PROXY_AUTHENTICATION_REQUIRED.0 == 24);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_408_REQUEST_TIME_OUT.0 == 25);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_409_CONFLICT.0 == 26);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_410_GONE.0 == 27);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_411_LENGTH_REQUIRED.0 == 28);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_412_PRECONDITION_FAILED.0 == 29);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_413_REQUEST_ENTITY_TOO_LARGE.0 == 30);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_414_REQUEST_URI_TOO_LARGE.0 == 31);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_415_UNSUPPORTED_MEDIA_TYPE.0 == 32);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_416_REQUESTED_RANGE_NOT_SATISFIED.0 == 33);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_417_EXPECTATION_FAILED.0 == 34);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_500_INTERNAL_SERVER_ERROR.0 == 35);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_501_NOT_IMPLEMENTED.0 == 36);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_502_BAD_GATEWAY.0 == 37);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_503_SERVICE_UNAVAILABLE.0 == 38);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_504_GATEWAY_TIME_OUT.0 == 39);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_505_VERSION_NOT_SUPPORTED.0 == 40);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_308_PERMANENT_REDIRECT.0 == 41);
assert!(uefi_raw::protocol::network::http::HttpStatusCode::STATUS_429_TOO_MANY_REQUESTS.0 == 42);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::INTERFACE_INFO.0 == 0);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::POLICY.0 == 1);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::MANUAL_ADDRESS.0 == 2);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::GATEWAY.0 == 3);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::DNS_SERVER.0 == 4);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2DataType::MAXIMUM.0 == 5);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Policy::STATIC.0 == 0);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Policy::DHCP.0 == 1);
assert!(uefi_raw::protocol::network::ip4_config2::Ip4Config2Policy::MAX.0 == 2);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::BOOTSTRAP.0 == 0);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::MS_WINNT_RIS.0 == 1);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::INTEL_LCM.0 == 2);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::DOS_UNDI.0 == 3);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::NEC_ESMPRO.0 == 4);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::IBM_WSOD.0 == 5);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::IBM_LCCM.0 == 6);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::CA_UNICENTER_TNG.0 == 7);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::HP_OPENVIEW.0 == 8);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::ALTIRIS_9.0 == 9);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::ALTIRIS_10.0 == 10);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::ALTIRIS_11.0 == 11);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::NOT_USED_12.0 == 12);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::REDHAT_INSTALL.0 == 13);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::REDHAT_BOOT.0 == 14);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::REMBO.0 == 15);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::BEOBOOT.0 == 16);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeBootType::PXETEST.0 == 65535);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::TFTP_FIRST.0 == 0);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::TFTP_GET_FILE_SIZE.0 == 1);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::TFTP_READ_FILE.0 == 2);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::TFTP_WRITE_FILE.0 == 3);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::TFTP_READ_DIRECTORY.0 == 4);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::MTFTP_GET_FILE_SIZE.0 == 5);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::MTFTP_READ_FILE.0 == 6);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::MTFTP_READ_DIRECTORY.0 == 7);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeTftpOpcode::MTFTP_LAST.0 == 8);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::ANY_SRC_IP.bits() == 1);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::ANY_SRC_PORT.bits() == 2);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::ANY_DEST_IP.bits() == 4);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::ANY_DEST_PORT.bits() == 8);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::USE_FILTER.bits() == 16);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeUdpOpFlags::MAY_FRAGMENT.bits() == 32);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Flags::BROADCAST.bits() == 1);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags::STATION_IP.bits() == 1);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags::BROADCAST.bits() == 2);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags::PROMISCUOUS.bits() == 4);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeIpFilterFlags::PROMISCUOUS_MULTICAST.bits() == 8);
assert!(uefi_raw::protocol::network::pxe::PxeBaseCodeDhcpV4Packet::DHCP_MAGIK == 1669485411);
assert!(uefi_raw::protocol::network::snp::ReceiveFlags::UNICAST.bits() == 1);
assert!(uefi_raw::protocol::network::snp::ReceiveFlags::MULTICAST.bits() == 2);
assert!(uefi_raw::protocol::network::snp::ReceiveFlags::BROADCAST.bits() == 4);
assert!(uefi_raw::protocol::network::snp::ReceiveFlags::PROMISCUOUS.bits() == 8);
assert!(uefi_raw::protocol::network::snp::ReceiveFlags::PROMISCUOUS_MULTICAST.bits() == 16);
assert!(uefi_raw::protocol::network::snp::InterruptStatus::RECEIVE.bits() == 1);
assert!(uefi_raw::protocol::network::snp::InterruptStatus::TRANSMIT.bits() == 2);
assert!(uefi_raw::protocol::network::snp::InterruptStatus::COMMAND.bits() == 4);
assert!(uefi_raw::protocol::network::snp::InterruptStatus::SOFTWARE.bits() == 8);
assert!(uefi_raw::protocol::network::snp::NetworkState::STOPPED.0 == 0);
assert!(uefi_raw::protocol::network::snp::NetworkState::STARTED.0 == 1);
assert!(uefi_raw::protocol::network::snp::NetworkState::INITIALIZED.0 == 2);
assert!(uefi_raw::protocol::network::snp::NetworkState::MAX_STATE.0 == 3);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::CLOSED.0 == 0);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::LISTEN.0 == 1);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::SYN_SENT.0 == 2);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::SYN_RECEIVED.0 == 3);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::ESTABLISHED.0 == 4);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::FIN_WAIT1.0 == 5);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::FIN_WAIT2.0 == 6);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::CLOSING.0 == 7);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::TIME_WAIT.0 == 8);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::CLOSE_WAIT.0 == 9);
assert!(uefi_raw::protocol::network::tcp4::Tcp4ConnectionState::LAST_ACK.0 == 10);
assert!(uefi_raw::protocol::network::tls::TlsConfigDataType::HOST_PUBLIC_CERT.0 == 0);
assert!(uefi_raw::protocol::network::tls::TlsConfigDataType::HOST_PRIVATE_KEY.0 == 1);
assert!(uefi_raw::protocol::network::tls::TlsConfigDataType::CA_CERTIFICATE.0 == 2);
assert!(uefi_raw::protocol::network::tls::TlsConfigDataType::CERT_REVOCATION_LIST.0 == 3);
assert!(uefi_raw::protocol::network::tls::TlsConfigDataType::MAXIMUM.0 == 4);
{ let actual = uefi_raw::protocol::network::dhcp4::Dhcp4Protocol::GUID.to_bytes(); let expected = [0x18, 0x97, 0x21, 0x8a, 0xf5, 0x4e, 0x61, 0x47, 0x91, 0xc8, 0xc0, 0xf0, 0x4b, 0xda, 0x9e, 0x56]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::dhcp4::Dhcp4Protocol::SERVICE_BINDING_GUID.to_bytes(); let expected = [0xd8, 0x39, 0x9a, 0x9d, 0x42, 0xbd, 0x73, 0x4a, 0xa4, 0xd5, 0x8e, 0xe9, 0x4b, 0xe1, 0x13, 0x80]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::http::HttpProtocol::GUID.to_bytes(); let expected = [0x9b, 0xb2, 0x59, 0x7a, 0x0b, 0x91, 0x71, 0x41, 0x82, 0x42, 0xa8, 0x5a, 0x0d, 0xf2, 0x5b, 0x5b]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::http::HttpProtocol::SERVICE_BINDING_GUID.to_bytes(); let expected = [0xaf, 0xe6, 0xc8, 0xbd, 0xbc, 0xd9, 0x79, 0x43, 0xa7, 0x2a, 0xe0, 0xc4, 0xe7, 0x5d, 0xae, 0x1c]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::ip4_config2::Ip4Config2Protocol::GUID.to_bytes(); let expected = [0xd1, 0x6e, 0x44, 0x5b, 0x0b, 0xe3, 0xaa, 0x4f, 0x87, 0x1a, 0x36, 0x54, 0xec, 0xa3, 0x60, 0x80]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::pxe::PxeBaseCodeProtocol::GUID.to_bytes(); let expected = [0x03, 0xe6, 0xc4, 0x03, 0x28, 0xac, 0xd3, 0x11, 0x9a, 0x2d, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0x4d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::snp::SimpleNetworkProtocol::GUID.to_bytes(); let expected = [0xb9, 0x32, 0x98, 0xa1, 0x25, 0xac, 0xd3, 0x11, 0x9a, 0x2d, 0x00, 0x90, 0x27, 0x3f, 0xc1, 0x4d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::tcp4::Tcp4Protocol::GUID.to_bytes(); let expected = [0xc7, 0x0b, 0x53, 0x65, 0x59, 0xa3, 0x0f, 0x41, 0xb0, 0x10, 0x5a, 0xad, 0xc7, 0xec, 0x2b, 0x62]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::tcp4::Tcp4Protocol::SERVICE_BINDING_GUID.to_bytes(); let expected = [0x65, 0x06, 0x72, 0x00, 0xeb, 0x67, 0x99, 0x4a, 0xba, 0xf7, 0xd3, 0xc3, 0x3a, 0x1c, 0x7c, 0xc9]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::tls::TlsConfigurationProtocol::GUID.to_bytes(); let expected = [0x44, 0xfe, 0x82, 0x16, 0x7a, 0xbd, 0x07, 0x44, 0xb7, 0xc7, 0xdc, 0xa3, 0x7c, 0xa3, 0x92, 0x2d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
{ let actual = uefi_raw::protocol::network::tls::TlsConfigurationProtocol::SERVICE_BINDING_GUID.to_bytes(); let expected = [0x95, 0xb7, 0x2c, 0x95, 0x36, 0xff, 0xcf, 0x48, 0xa2, 0x49, 0x4d, 0xf4, 0x86, 0xd6, 0xab, 0x8d]; let mut i = 0; while i < 16 { assert!(actual[i] == expected[i]); i += 1; } }
};
