#!/usr/bin/env python3
"""Generate reviewed inert fixed-table records and bounded field decoders."""
import argparse
from pathlib import Path
import re
from fixed_model import ROOT, PIN, records, rust_measure

DEST=ROOT/'source/libraries/acpi'
HEADER='// SPDX-License-Identifier: MIT OR Apache-2.0\n// Modified pinned acpi data declarations/field decoding at '+PIN+'.\n// Generated by tools/ports/acpi/fixed_generate.py; see fixed.PORT.md.\n'
ALIASES={'FixedFeatureFlags':'u32','IaPcBootArchFlags':'u16','ArmBootArchFlags':'u16'}


def snake(name):return re.sub(r'(?<!^)(?=[A-Z])','_',name).lower()

def carrier(field,record):
    typ=field['type']
    if typ=='PhantomPinned':return None
    if typ.startswith('ExtendedField<u64'):return 'OptionalU64'
    if typ.startswith('ExtendedField<u16'):return 'OptionalU16'
    if typ.startswith('ExtendedField<RawGenericAddress') or record=='Fadt' and field['name']=='reset_reg':return 'OptionalRawGas'
    return ALIASES.get(typ,typ)


def render():
    model=records();measure=rust_measure(model)
    types=HEADER+'module fixed_types;\nuse headers::SdtHeader;\nuse gas::RawGenericAddress;\nuse gas::OptionalRawGas;\nuse fixed_bytes::OptionalU16;\nuse fixed_bytes::OptionalU64;\n'
    decode=HEADER+'module fixed_decode;\nuse headers::SdtHeader;\n'
    for name in ['U8Result','U16Result','U32Result','U64Result','OptionalU16','OptionalU64','read_u8','read_u16','read_u32','read_u64']:
        decode+='use fixed_bytes::'+name+';\n'
    for name in ['RawGenericAddress','RawGasResult','OptionalRawGas','parse_gas']:decode+='use gas::'+name+';\n'
    for name in model:
        if name=='RawGenericAddress':continue
        decode+='use fixed_types::'+name+';\n'
        if name not in ['EntryHeader','MultiprocessorWakeupMailbox']:decode+='use fixed_types::'+name+'Result;\n'
    for name,row in model.items():
        if name=='RawGenericAddress':continue
        types+=f'pub data {name} [copy] {{\n'
        for field in row['fields']:
            typ=carrier(field,name)
            if typ:types+=f"    {field['name'].lstrip('_')}: {typ};\n"
        if name=='Fadt':types+='    has_reset: bool; has_arm_boot_arch: bool; has_minor_version: bool;\n'
        if name=='GiccEntry':types+='    has_efficiency_class: bool; has_spe: bool;\n'
        types+='}\n'
        if name in ['EntryHeader','MultiprocessorWakeupMailbox']:continue
        types+=f'pub data {name}Result [copy] {{ error: u8; value: {name}; }}\n'
        header_type='SdtHeader' if name in ['Fadt','Madt','Mcfg','HpetTable'] else 'EntryHeader' if name!='McfgEntry' else None
        params=f', header: {header_type}'if header_type else ''
        params+=', revision: u8' if name=='GiccEntry' else ''
        args=', header' if header_type else ''
        args+=', revision' if name=='GiccEntry' else ''
        decode+=f'pub machine decode_{snake(name)}(input: &[u8; 4096], length: u64, offset: u64{params}) -> {name}Result {{\n'
        decode+='    transition offset <= 4096 { true -> fields(input, length, offset'+args+f') _ -> ({name}Result {{ error: 2 }}) }}\n'
        decode+=f'    state fields(input: &[u8; 4096], length: u64, offset: u64{params}) -> {name}Result {{\n'
        fields=[f for f in row['fields'] if f['name']!='header' and carrier(f,name)]
        # All exact offset arithmetic precedes calls, preserving explicit bounds.
        for f in fields:
            field=f['name'];local=field.lstrip('_');pos=measure[name+'.'+field]
            array=re.fullmatch(r'\[u8; (\d+)\]',f['type'])
            if array:
                for i in range(int(array[1])):decode+=f'        let o_{local}_{i}: u64 = offset + {pos+i};\n'
            else:decode+=f'        let o_{local}: u64 = offset + {pos};\n'
        required=[];values=[]
        if header_type:values.append('header: header')
        for f in fields:
            local=f['name'].lstrip('_');typ=f['type'];out=carrier(f,name);pos=measure[name+'.'+f['name']]
            array=re.fullmatch(r'\[u8; (\d+)\]',typ)
            if array:
                n=int(array[1])
                for i in range(n):
                    decode+=f'        let r_{local}_{i}: U8Result = read_u8(input, length, o_{local}_{i});\n'
                    required.append(f'r_{local}_{i}.error == 0')
                value='['+', '.join(f'r_{local}_{i}.value'for i in range(n))+']'
            else:
                inner=re.match(r'ExtendedField<([^,]+),',typ)
                readtype=ALIASES.get(inner[1] if inner else typ,inner[1] if inner else typ)
                result='RawGasResult' if readtype=='RawGenericAddress' else readtype.upper()+'Result'
                machine='parse_gas' if readtype=='RawGenericAddress' else 'read_'+readtype
                decode+=f'        let r_{local}: {result} = {machine}(input, length, o_{local});\n'
                optional=name=='Fadt' and pos>=116 or name=='GiccEntry' and pos>=76
                if not optional:required.append(f'r_{local}.error == 0')
                value=f'r_{local}.value'
                if out.startswith('Optional'):
                    rev=6 if local in ['hypervisor_vendor_id','trbe_interrupt'] else 5 if local in ['sleep_control_reg','sleep_status_reg'] else 2
                    revexpr='revision' if name=='GiccEntry' else 'header.revision'
                    value=f'{out} {{ present: {revexpr} >= {rev} && r_{local}.error == 0, value: r_{local}.value }}'
            values.append(local+': '+value)
        if name=='Fadt':values+=['has_reset: header.revision >= 2 && r_reset_reg.error == 0 && r_reset_value.error == 0',
                                'has_arm_boot_arch: header.revision >= 5 && r_arm_boot_arch.error == 0',
                                'has_minor_version: header.revision >= 5 && r_fadt_minor_version.error == 0']
        if name=='GiccEntry':values+=['has_efficiency_class: r_processor_power_efficiency_class.error == 0 && r_reserved2.error == 0 && r_spe_overflow_interrupt.error == 0',
                                     'has_spe: r_spe_overflow_interrupt.error == 0']
        decode+='        transition '+' && '.join(required)+' {\n'
        decode+=f'            true -> ({name}Result {{ value: {name} {{\n                '+',\n                '.join(values)+' } })\n'
        decode+=f'            _ -> ({name}Result {{ error: 2 }})\n        }}\n    }}\n}}\n'
    return {'fixed_types.omg':types,'fixed_decode.omg':decode}


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,text in render().items():
        path=DEST/name
        if args.check:
            if not path.exists() or path.read_text()!=text:raise SystemExit('generated source differs: '+str(path))
        else:path.write_text(text)
    print('Fixed record declarations and bounded field decoders '+('verified'if args.check else 'generated'))


if __name__=='__main__':main()
