[workspace]
resolver = "3"
members = [
    # Contracts
    "contracts",
    # Kernel
    "kernel/arch",
    "kernel/boot/uefi",
    "kernel/core",
    # Platform
    "platform/drivers/ata-pio",
    "platform/drivers/uart_16550",
    "platform/libraries/bitmap-font",
    "platform/libraries/object-store",
    "platform/libraries/user-runtime",
    "platform/services/display",
    "platform/services/input",
    "platform/services/storage",
    # Distribution
    "distribution/applications/status",
    "distribution/applications/counter",
    "distribution/init",
    "distribution/lab/display",
    "distribution/lab/compositor",
    "distribution/lab/hello",
    "distribution/lab/ipc",
    "distribution/lab/memory",
    "distribution/lab/rendering",
    "distribution/lab/supervision",
    "distribution/libraries/boot-scene",
    "distribution/libraries/session-protocol",
]
default-members = ["distribution/lab/rendering", "platform/libraries/object-store", "contracts", "kernel/core", "platform/services/input", "platform/services/display", "platform/libraries/bitmap-font"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace.dependencies]
cathedral-ata-pio = { path = "platform/drivers/ata-pio" }
cathedral-object-store = { path = "platform/libraries/object-store" }
cathedral-storage-service = { path = "platform/services/storage" }
cathedral-session-protocol = { path = "distribution/libraries/session-protocol" }
cathedral-bitmap-font = { path = "platform/libraries/bitmap-font" }
cathedral-contracts = { path = "contracts" }
cathedral-core = { path = "kernel/core" }
cathedral-uart-16550 = { path = "platform/drivers/uart_16550" }
cathedral-arch = { path = "kernel/arch" }
cathedral-user-runtime = { path = "platform/libraries/user-runtime" }
cathedral-boot-scene = { path = "distribution/libraries/boot-scene" }
uefi = { version = "0.41.0", default-features = false }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2
