[workspace]
resolver = "3"
members = ["boot/uefi", "contracts", "core", "drivers/uart_16550", "libraries/x86_64"]
default-members = ["contracts", "core"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace.dependencies]
cathedral-contracts = { path = "contracts" }
cathedral-core = { path = "core" }
cathedral-uart-16550 = { path = "drivers/uart_16550" }
cathedral-x86-64 = { path = "libraries/x86_64" }
uefi = { version = "0.41.0", default-features = false }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2

