[workspace]
resolver = "3"
members = ["kernel/arch", "kernel/boot/uefi", "contracts", "kernel/core", "platform/drivers/uart_16550", "platform/libraries/user-runtime", "distribution/programs/hello", "distribution/programs/ipc", "distribution/programs/supervision", "platform/services/display", "distribution/programs/display", "distribution/init", "distribution/libraries/boot-scene", "platform/services/input"]
default-members = ["contracts", "kernel/core", "platform/services/input"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.94"
publish = false

[workspace.dependencies]
cathedral-contracts = { path = "contracts" }
cathedral-core = { path = "kernel/core" }
cathedral-uart-16550 = { path = "platform/drivers/uart_16550" }
cathedral-arch = { path = "kernel/arch" }
cathedral-user-runtime = { path = "platform/libraries/user-runtime" }
cathedral-boot-scene = { path = "distribution/libraries/boot-scene" }
uefi = { version = "0.41.0", default-features = false }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = 2
