[package]
name = "cathedral-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
cathedral-contracts.workspace = true
cathedral-arch.workspace = true
linked_list_allocator = "0.10.6"

[lints]
workspace = true
